# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 sts=2 et :

require 'vagrant-openstack-provider'

Vagrant.configure("2") do |config|

  config.vm.provider :openstack do |os, override|

    os.openstack_auth_url = 'https://auth.vexxhost.net/v2.0/'
    os.flavor = 'v1-standard-4'
    os.region = 'ca-ymq-1'
    os.availability_zone = 'ca-ymq-2'

    # https://secure.vexxhost.com/console/#/account/credentials
    os.tenant_name = ENV['OS_TENANT_NAME']
    os.username = ENV['OS_USERNAME']
    os.password = ENV['OS_PASSWORD']

    # CPPROJECT=fdio
    # NETID=$(nova network-list | awk '/${CPPROJECT}/ {print $2}')
    os.networks = ENV['NETID']

    # personal default instance names
    os.server_name = 'kf7bmp-vagrant'
  end
end
